### PR TITLE
fix for checkptr

### LINKED ISSUE #99: "fatal error: checkptr: unsafe pointer conversion" with Go 1.14 und race detector
Running ws compiled with Go 1.14 under the race detector (e.g. during `go test -race`) aborts with the following error:

```
fatal error: checkptr: unsafe pointer conversion

goroutine 122 [running]:
runtime.throw(0x1f0854e, 0x23)
	/usr/local/go/src/runtime/panic.go:1112 +0x72 fp=0xc00062cdd0 sp=0xc00062cda0 pc=0x1073eb2
runtime.checkptrAlignment(0xc000448035, 0x1d8b100, 0x1)
	/usr/local/go/src/runtime/checkptr.go:13 +0xd0 fp=0xc00062ce00 sp=0xc00062cdd0 pc=0x1045ba0
github.com/gobwas/ws.btsEqualFold(0xc000448034, 0x9, 0xfcc, 0x2818c38, 0x9, 0x9, 0xc000448034)
	/Users/m0252720/go/pkg/mod/github.com/gobwas/ws@v1.0.2/util.go:233 +0x184 fp=0xc00062ce68 sp=0xc00062ce00 pc=0x1c42ee4
github.com/gobwas/ws.Dialer.Upgrade(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/m0252720/go/pkg/mod/github.com/gobwas/ws@v1.0.2/dialer.go:374 +0xe72 fp=0xc00062d0f8 sp=0xc00062ce68 pc=0x1c3dfd2
github.com/gobwas/ws.Dialer.Dial(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/m0252720/go/pkg/mod/github.com/gobwas/ws@v1.0.2/dialer.go:190 +0x444 fp=0xc00062d480 sp=0xc00062d0f8 pc=0x1c3c2e4
github.com/gobwas/ws.Dial(...)
	/Users/m0252720/go/pkg/mod/github.com/gobwas/ws@v1.0.2/dialer.go:47
```

Go 1.14 added a new checkptr compile time option which tests for proper handling of unsafe.Pointer values, see https://golang.org/doc/go1.14#compiler for details.
It seems as if ws doesn't follow the unsafe.Pointer safety guidelines strictly enough.

The problem can be reproduced on master:

    $ GO111MODULE=off go test -race github.com/gobwas/ws

### PR DESCRIPTION
**Pull request by cristaloleg**
Fixes #99

### CODE REVIEW

File: util.go [hunk 1]
```diff
@@ -230,8 +230,8 @@ func btsEqualFold(s, p []byte) bool {
 
 	for i := 0; i < n; i++ {
 		x := m + (i << 3)
-		av := *(*uint64)(unsafe.Pointer(&s[x]))
-		bv := *(*uint64)(unsafe.Pointer(&p[x]))
+		av := uint64(*(*byte)(unsafe.Pointer(&s[x])))
```
Comment (gobwas) [inline util.go]: Looks like it is not correct replacement? Its a casting of `byte` value to `uint64`? Or am I misunderstood this?

File: cipher.go [hunk 2]
```diff
@@ -46,8 +47,10 @@ func Cipher(payload []byte, mask [4]byte, offset int) {
 	// Get number of uint64 parts remaining to process.
 	n = (n - ln - rn) >> 3
 	for i := 0; i < n; i++ {
-		v := (*uint64)(unsafe.Pointer(&payload[ln+(i<<3)]))
-		*v = *v ^ m2
+		idx := ln + (i << 3)
+		p := binary.LittleEndian.Uint64(payload[idx : idx+8])
+		p = p ^ m2
+		binary.LittleEndian.PutUint64(payload[idx:idx+8], p)
```
Comment (gobwas) [inline cipher.go]: Actually this is a little bit slower than we had, but it is the best solution for now I think. Thank you!

File: util.go (hunk 1 above)
Comment (gobwas) [reply util.go]: I mean, is it the same as just doing `uint64(p[x])`?

Comment (cristaloleg) [reply util.go]: Hm, yeah, probably this can be reduced to `uint64(p[x])`. I will double check this a bit later 👌

Comment (gobwas) [reply util.go]: I mean, it can't  – prev implementation was comparing all 8 bytes, this change will compare only one :)
I believe as an extreme thing we may moreover replace this `btsEqualFold` and `strEqualFold` to the stdlib alternatives – there are not so much difference in performance in cases where these functions used (mostly for checking short strings):

```
BenchmarkBtsEqualFold/websocket#0-12                            213459022                5.58 ns/op            0 B/op          0 allocs/op
BenchmarkBtsEqualFold/upgrade#1-12                              134671761                8.86 ns/op            0 B/op          0 allocs/op
BenchmarkBtsEqualFold/rnd_eq_512#2-12                           23062928                52.0 ns/op             0 B/op          0 allocs/op
BenchmarkBtsEqualFold/rnd_ineq_512_256#3-12                     40835487                28.1 ns/op             0 B/op          0 allocs/op

BenchmarkBtsEqualFold/websocket#0_std-12                        43955514                26.4 ns/op             0 B/op          0 allocs/op
BenchmarkBtsEqualFold/upgrade#1_std-12                          56361006                19.6 ns/op             0 B/op          0 allocs/op
BenchmarkBtsEqualFold/rnd_eq_512#2_std-12                         722638              1595 ns/op               0 B/op          0 allocs/op
BenchmarkBtsEqualFold/rnd_ineq_512_256#3_std-12                  1471777               806 ns/op               0 B/op          0 allocs/op
```

That is, we never use them on some long strings.

Comment (cristaloleg) [reply util.go]: Oh, looks good. So I will update method with funcs mentioned by you.

File: util.go [hunk 3]
```diff
@@ -230,8 +230,8 @@ func btsEqualFold(s, p []byte) bool {
 
 	for i := 0; i < n; i++ {
 		x := m + (i << 3)
-		av := uint64(*(*byte)(unsafe.Pointer(&s[x])))
-		bv := uint64(*(*byte)(unsafe.Pointer(&p[x])))
+		av := uint64(s[x])
```
Comment (gobwas) [inline util.go]: I believe we have misunderstanding in the previous discussion :)
So I will explain in details.
Previous version does this:
- treat **first 8 bytes** as uint64([ b1 b2 ... b8 ])
- apply mask to it
- take next **8 bytes**

Current version in PR does this:
- treat **first byte** as uint64([ b1 ])
- apply mask to it
- take next **8 bytes**

So we loose 7 bytes here.

Comment (gobwas) [reply util.go]: What I suggest is just to remove use of this `btsEqualFold()` and `strEqualFold()` and substitute them with `bytes.EqualFold()` and `strings.EqualFold()`.

**Comment by cristaloleg** [comment]
Sorry for the not a full change, have pushed old commit. And sorry for the delay.

**Comment by gobwas** [comment]
Thank you so much! 🍾 
No worries at all! 👍
